version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mylist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mylist
      MYSQL_DATABASE: mylist
      MYSQL_USER: mylist
      MYSQL_PASSWORD: mylist
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: mylist-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
